language: node_js

node_js:
  - 6

sudo: false

cache:
  directories:
  - dist/node_modules
  - dist/bower_components

before_install:
- cd dist/
  npm install -g npm@latest-2
  npm --version

script:
  - npm run lint -s
